apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-suite-config
  namespace: devops-suite
data:
  DB_URL: "jdbc:postgresql://postgres-service:5432/devopssuite"
  DB_USERNAME: "postgres"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  ELASTICSEARCH_HOST: "elasticsearch-service"
  ELASTICSEARCH_PORT: "9200"
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-suite-secrets
  namespace: devops-suite
type: Opaque
stringData:
  DB_PASSWORD: "password"
  JWT_SECRET: "your-secret-key-minimum-256-bits-which-is-super-long"
  GOOGLE_CLIENT_ID: "dummy-id"
  GOOGLE_CLIENT_SECRET: "dummy-secret"
